### ISSUE TITLE
Changing Recipe doesnt change Building

### ISSUE THREAD

**Issue by nomis14** [satisfactory-factories/application#312] opened 2024-12-22 13:50 UTC
Hi,
I noticed that changing the Recipe with one that uses a different building, for example Iron Ingot to Pure Iron Ingot, it displays the wrong Building.
![grafik](https://github.com/user-attachments/assets/4bab1ae2-6891-4b09-9bf8-5f9e98593fa2)
 The JSON is correct:
"products": [
    {
      "id": "IronIngot",
      "amount": 1,
      "recipe": "Alternate_PureIronIngot",
      "displayOrder": 0,
      "requirements": {
        "OreIron": {
          "amount": 0.538
        },
        "Water": {
          "amount": 0.308
        }
      },
      "buildingRequirements": {
        "name": "oilrefinery",
        "amount": 0.015384615384615385,
        "powerConsumed": 0.12038720370730982
      },
      "byProducts": []
    }
  ],
It just seems that the Image just isnt being replaced when the Recipe changes.

**Comment by Maelstromeous** [comment] 2024-12-22 13:53
Duplicate of #259.

**Closed** 2024-12-22 13:53 UTC
Labels: Needs Triage
